ТЗ 11 первый коммит для отправки на ревью!
AzamatKarabashev/java-filmorate pull request #7
Opened 2023-12-16 11:07 UTC by AzamatKarabashev

2023-12-17 02:38 UTC, AzamatKarabashev commented
ТЗ 11 Внесение изменений в README.md
прикрепили схемку к гиту, в виду неопытности сделали это методом merge to main
а нужно было просто коммитом сюда идти

2023-12-17 07:58 UTC, avlin87 requested changes
Привет, Азамат,
Впечатляющий результат. Продолжай в том же духе 👍 .
Комментариев всего 3.

2023-12-17 07:58 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/controller/api/GenreController.java
> +        log.info("GET request received to receive  all genres");
Давай логирование самого факта вызова `api` изменим на `debug`.
Логирование в целом может значительно замедлить приложение. По этому лучше поставить такой уровень логирования, который при обычной работе приложения не будет выводиться.

В этом и других контроллерах, если есть логирование.

2023-12-17 07:58 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/model/Genre.java
> +@Component
Убери, пожалуйста, `@Component` из классов моделей.
Вижу из Film уже убрал её.

`@Component` создаст один объект в Spring и если будет где-то ожидаться `@Autowired` подобный объект, то предоставит его.

2023-12-17 07:58 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/storage/daoImpl/MpaStorageImpl.java
> +        String query = "SELECT * FROM Mpa";
`*можно лучше*`
лучше не использовать `*` в своих запросах, так как мы получим все поля таблицы.
1. Кто-то может напрямую добавить колонку в таблицу в базе данных и поля запроса перестанут совпадать с полями нашей модели.
2. У запросов с конкретными именами колонок лучше производительность
3. и просто увеличится читаемость при использовании имен колонок.

Хорошо бы поправить во всех подобных местах.

2023-12-17 09:20 UTC, AzamatKarabashev commented
убрали все не используемые аннотации,
в частности @Component над сущностями, ранее предполагалось накидать побольше что бы работало! пришло понимание, спасибо лучшему!
также добавили логов с уровнем debug в классы контроллеры UserController и FilmController.
изменили ранее вызываемые логи с уровня инфо на уровень дебаг, в следствии меньшего спама в логах и было принято решение накидать в вышеуказанные классы логов 
Также, более мы не вызываем в таблицах все поля через *, теперь они явно указаны!
Лучшему спасибо еще раз!

2023-12-18 01:29 UTC, avlin87 approved these changes
Работу принимаю.

2023-12-18 09:06 UTC, merged